services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    expose:
      - "8080"
    ports:
      - "8333:8080"
    volumes:
      - "./open-webui:/app/backend/data"
    environment:
      OLLAMA_BASE_URL: https://ai-api.samanware.com/
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
