services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:80"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=https://ai-api.samanware.com
    restart: unless-stopped

volumes:
  ollama:
  open-webui:
