services:
  deepseek:
    image: byron758/woohengine-deepseek:1.1
    container_name: deepseek-container
    restart: unless-stopped
    ports:
      # - "4000:80"        # Apache Web Server
      - "11434:11434" # Ollama API

    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
